apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-service
  labels:
    app: match-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-service
  template:
    metadata:
      labels:
        app: match-service
    spec:
      containers:
        - name: match-service
          image: match-service:latest
          ports:
            - containerPort: 9093